services:
  # Database
  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql_data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PW}
      MYSQL_DATABASE: testdb
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PW}
    networks:
      - mysql-phpmyadmin

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    # restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PW}
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  mysql-data:
