services:
  # Database
  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init_mysql.sh:/docker-entrypoint-initdb.d/init.sh
    # restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: datascience_pbl
      MYSQL_ROOT_PASSWORD: ${DB_PW}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PW}
      MYSQL_ROOT_HOST: '%'
    networks:
      - mysql-phpmyadmin

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    # restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PW}
      MYSQL_ROOT_PASSWORD: ${DB_PW}
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  mysql-data:
